version: '2'
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - mysql
    networks:
      default:
        ipv4_address: 10.2.10.15

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      default:
        ipv4_address: 10.2.10.17

  nodejs:
    build:
      context: ./nodejs
    restart: "no"
    container_name: nodejs
    networks:
      default:
        ipv4_address: 10.2.10.20
    environment:
      - NAME=NODEJS

  nginx:
    build:
      context: ./nginx
    restart: "no"
    container_name: nginx
    networks:
      default:
        ipv4_address: 10.2.10.30

  proxy:
    image: haproxy:1.5
    restart: "no"
    container_name: proxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      default:
        ipv4_address: 10.2.10.100
    depends_on:
      - wordpress

networks:
  default:
    ipam:
      config:
      - subnet: "10.2.10.1/25"
