apiVersion: v1
kind: Service
metadata:
  name: %STACK_NAME%-nginx
  labels:
    app: %STACK_NAME%-nginx
spec:
  ports:
    - port: 80
  selector:
    app: %STACK_NAME%-nginx
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %STACK_NAME%-nginx
  labels:
    app: %STACK_NAME%-nginx
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: %STACK_NAME%-nginx
        tier: frontend
    spec:
      containers:
      - image: %ECR_REPO%/nginx:latest
        name: %STACK_NAME%-nginx
        ports:
        - containerPort: 80