apiVersion: v1
kind: Service
metadata:
  name: %STACK_NAME%-nodejs
  labels:
    app: %STACK_NAME%-nodejs
spec:
  ports:
    - port: 8080
  selector:
    app: %STACK_NAME%-nodejs
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %STACK_NAME%-nodejs
  labels:
    app: %STACK_NAME%-nodejs
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: %STACK_NAME%-nodejs
        tier: frontend
    spec:
      containers:
      - image: %ECR_REPO%/nodejs:latest
        name: %STACK_NAME%-nodejs
        ports:
        - containerPort: 8080