apiVersion: v1
kind: Service
metadata:
  name: %STACK_NAME%-wordpress
  labels:
    app: %STACK_NAME%-wordpress
spec:
  ports:
    - port: 80
  selector:
    app: %STACK_NAME%-wordpress
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %STACK_NAME%-wordpress
  labels:
    app: %STACK_NAME%-wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: %STACK_NAME%-wordpress
        tier: frontend
    spec:
      containers:
      - image: %ECR_REPO%/wordpress:latest
        name: %STACK_NAME%-wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "%STACK_NAME%-mysql"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        - name: WORDPRESS_DB_USER
          value: "wordpress"
        - name: WORDPRESS_DB_PASSWORD
          value: "password"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: %STACK_NAME%-wordpress-volume
          mountPath: /var/www/html/blog
      volumes:
      - name: %STACK_NAME%-wordpress-volume
        awsElasticBlockStore:
          volumeID: %WP_EBS_VOLUME_ID%
          fsType: ext4