apiVersion: v1
kind: Service
metadata:
  name: fresh-nginx
  labels:
    app: fresh-nginx
spec:
  ports:
    - port: 80
  selector:
    app: fresh-nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fresh-nginx
  labels:
    app: fresh-nginx
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fresh-nginx
        tier: frontend
    spec:
      containers:
      - image: kopachevsky/ai-nginx
        name: fresh-nginx
        ports:
        - containerPort: 80